server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/place_administration
    username: Wassem
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

