server:
  tomcat:
    accesslog:
      enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      defer-datasource-initialization: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc.lob.non_contextual_creation: true
    show_sql: true
  servlet:
    multipart:
      max-file-size: 1650MB
      max-request-size: 1650MB
  datasource:
    url: jdbc:postgresql://dpg-co8ldiv109ks73egl4o0-a.oregon-postgres.render.com/place_administration_stage_3
    username: wassem
    password: jIMGH1AsW7vTj4r0NPLM1fQ5UYw31gpO