server:
  tomcat:
    accesslog:
      enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://dpg-cnf76ila73kc7391gtj0-a.oregon-postgres.render.com/place_administration
    username: wassem
    password: ZkBgyHXWV0MbOI7O2JH6vXumEw6mBI87